/*
 * Bonus Operations API for MobileAplication
 *
 * This microservice allows you to receive information about transactions in the MKB bonus
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class BonusOperationsReportScreenResponseOperationListPageFilters : IEquatable<BonusOperationsReportScreenResponseOperationListPageFilters>
    { 
        /// <summary>
        /// Параметр принимает в себя одно из двух значений \&quot;enrollment\&quot;(При зачислении баллов) || \&quot;accrual\&quot;(При спсиании баллов)
        /// </summary>
        /// <value>Параметр принимает в себя одно из двух значений \&quot;enrollment\&quot;(При зачислении баллов) || \&quot;accrual\&quot;(При спсиании баллов)</value>

        [DataMember(Name="enrollmentType")]
        public string EnrollmentType { get; set; }

        /// <summary>
        /// Заполняется уникальными значениями парметра \&quot;enrollmentType\&quot; из ответа сервиса MKBO_GET_BONUS_OPERATIONS_LIST_MKBO2MCBBO
        /// </summary>
        /// <value>Заполняется уникальными значениями парметра \&quot;enrollmentType\&quot; из ответа сервиса MKBO_GET_BONUS_OPERATIONS_LIST_MKBO2MCBBO</value>

        [DataMember(Name="name")]
        public string Name { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BonusOperationsReportScreenResponseOperationListPageFilters {\n");
            sb.Append("  EnrollmentType: ").Append(EnrollmentType).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((BonusOperationsReportScreenResponseOperationListPageFilters)obj);
        }

        /// <summary>
        /// Returns true if BonusOperationsReportScreenResponseOperationListPageFilters instances are equal
        /// </summary>
        /// <param name="other">Instance of BonusOperationsReportScreenResponseOperationListPageFilters to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BonusOperationsReportScreenResponseOperationListPageFilters other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    EnrollmentType == other.EnrollmentType ||
                    EnrollmentType != null &&
                    EnrollmentType.Equals(other.EnrollmentType)
                ) && 
                (
                    Name == other.Name ||
                    Name != null &&
                    Name.Equals(other.Name)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (EnrollmentType != null)
                    hashCode = hashCode * 59 + EnrollmentType.GetHashCode();
                    if (Name != null)
                    hashCode = hashCode * 59 + Name.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(BonusOperationsReportScreenResponseOperationListPageFilters left, BonusOperationsReportScreenResponseOperationListPageFilters right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(BonusOperationsReportScreenResponseOperationListPageFilters left, BonusOperationsReportScreenResponseOperationListPageFilters right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
