/*
 * Bonus Operations API for MobileAplication
 *
 * This microservice allows you to receive information about transactions in the MKB bonus
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// Объект содержащий ифномрацию для отрисовки хедера расширинной операции
    /// </summary>
    [DataContract]
    public partial class ExpandedOperationHeader : IEquatable<ExpandedOperationHeader>
    { 
        /// <summary>
        /// Gets or Sets Icon
        /// </summary>

        [DataMember(Name="icon")]
        public ExpandedOperationHeaderIcon Icon { get; set; }

        /// <summary>
        /// Заполянется конкатенацией строк \&quot;bonusValue.amounth + баллов\&quot; ответа сервиса MKBO_GET_BONUS_OPERATION_MKBO2MCBBO
        /// </summary>
        /// <value>Заполянется конкатенацией строк \&quot;bonusValue.amounth + баллов\&quot; ответа сервиса MKBO_GET_BONUS_OPERATION_MKBO2MCBBO</value>

        [DataMember(Name="bonusValue")]
        public string BonusValue { get; set; }

        /// <summary>
        /// Заполянется значением поля \&quot;operationID\&quot; ответа сервиса MKBO_GET_BONUS_OPERATION_MKBO2MCBBO
        /// </summary>
        /// <value>Заполянется значением поля \&quot;operationID\&quot; ответа сервиса MKBO_GET_BONUS_OPERATION_MKBO2MCBBO</value>

        [DataMember(Name="merchName")]
        public string MerchName { get; set; }

        /// <summary>
        /// Gets or Sets OperationState
        /// </summary>

        [DataMember(Name="operationState")]
        public ExpandedOperationHeaderOperationState OperationState { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ExpandedOperationHeader {\n");
            sb.Append("  Icon: ").Append(Icon).Append("\n");
            sb.Append("  BonusValue: ").Append(BonusValue).Append("\n");
            sb.Append("  MerchName: ").Append(MerchName).Append("\n");
            sb.Append("  OperationState: ").Append(OperationState).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ExpandedOperationHeader)obj);
        }

        /// <summary>
        /// Returns true if ExpandedOperationHeader instances are equal
        /// </summary>
        /// <param name="other">Instance of ExpandedOperationHeader to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ExpandedOperationHeader other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Icon == other.Icon ||
                    Icon != null &&
                    Icon.Equals(other.Icon)
                ) && 
                (
                    BonusValue == other.BonusValue ||
                    BonusValue != null &&
                    BonusValue.Equals(other.BonusValue)
                ) && 
                (
                    MerchName == other.MerchName ||
                    MerchName != null &&
                    MerchName.Equals(other.MerchName)
                ) && 
                (
                    OperationState == other.OperationState ||
                    OperationState != null &&
                    OperationState.Equals(other.OperationState)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Icon != null)
                    hashCode = hashCode * 59 + Icon.GetHashCode();
                    if (BonusValue != null)
                    hashCode = hashCode * 59 + BonusValue.GetHashCode();
                    if (MerchName != null)
                    hashCode = hashCode * 59 + MerchName.GetHashCode();
                    if (OperationState != null)
                    hashCode = hashCode * 59 + OperationState.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ExpandedOperationHeader left, ExpandedOperationHeader right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ExpandedOperationHeader left, ExpandedOperationHeader right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
